canton.remote-participants.participant_app_provider {
  ledger-api {
    address = canton
    port = 3${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  }

  admin-api {
    address = canton
    port = 3${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
  }
}

canton.remote-sequencers.sequencer_app {
  public-api {
    address = canton
    port = 5018
  }

  admin-api {
    address = canton
    port = 5019
  }
}

canton.remote-mediators.mediator_app {

  admin-api {
    address = canton
    port = 5017
  }
}
